CREATE OR REPLACE TABLE AOL_SCHEMA.WC_QUERYDIM (
    QUERY VARCHAR(5000) NOT NULL,
    ID DECIMAL(18) NOT NULL Primary Key
);

CREATE OR REPLACE TABLE AOL_SCHEMA.PLAYER_QUERYDIM (
    QUERY VARCHAR(5000) NOT NULL,
    ID DECIMAL(18) NOT NULL Primary Key
);

CREATE OR REPLACE TABLE AOL_SCHEMA.TEAMDIM (
    ID DECIMAL(18) NOT NULL Primary Key,
    TEAM VARCHAR(256) NOT NULL,
    RANK DECIMAL(18) NOT NULL
);

CREATE OR REPLACE TABLE AOL_SCHEMA.PLAYER_MATCHDIM (
    ID DECIMAL(18) NOT NULL Primary Key,
    GOALS DECIMAL(18) NOT NULL,
    RED_CARDS DECIMAL(18) NOT NULL,
    YELLOW_CARDS DECIMAL(18) NOT NULL
);

CREATE OR REPLACE TABLE AOL_SCHEMA.MATCHDIM (
    ID DECIMAL(18) NOT NULL Primary Key,
    HOME_TEAM_NAME VARCHAR(256) NOT NULL,
    AWAY_TEAM_NAME VARCHAR(256) NOT NULL,
    HOME_TEAM_GOALS DECIMAL(18) NOT NULL,
    AWAY_TEAM_GOALS DECIMAL(18) NOT NULL,
    ATTENDANCE DECIMAL(18) NOT NULL
);

CREATE OR REPLACE TABLE AOL_SCHEMA.LOCATIONDIM (
    ID DECIMAL(18) NOT NULL Primary Key,
    CITY VARCHAR(256) NOT NULL,
    STADIUM VARCHAR(256) NOT NULL
);

CREATE OR REPLACE TABLE AOL_SCHEMA.PLAYERDIM (
    ID DECIMAL(18) NOT NULL Primary Key,
    PLAYER_NAME VARCHAR(256) NOT NULL
);

CREATE OR REPLACE TABLE AOL_SCHEMA.MATCH_FACTS (
    MATCH_ID DECIMAL(18) NOT NULL,
    PLAYER_MATCH_ID DECIMAL(18) NOT NULL,
    PLAYER_ID DECIMAL(18) NOT NULL,
    TIME_ID DECIMAL(18) NOT NULL,
    TEAM_ID DECIMAL(18) NOT NULL,
    LOCATION_ID DECIMAL(18) NOT NULL
);
